# Generated by Django 5.2.6 on 2026-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='package',
            field=models.CharField(choices=[('1000', 'Chatbots'), ('2000', 'Mobile Dev'), ('3000', 'Web Dev'), ('custom', 'Custom items')], max_length=20),
        ),
    ]
