# Generated by Django 5.2.6 on 2026-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_lead_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='package',
            field=models.CharField(choices=[('chatbots', 'Chatbots'), ('consult', 'AI Consultation'), ('automation', 'Workflow Automation'), ('mobile', 'Mobile Dev'), ('web', 'Web Dev'), ('analytics', 'Data Analysis'), ('mldl', 'ML DLTasks'), ('custom', 'Custom items')], max_length=20),
        ),
    ]
